# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import tra_pb2 as tra__pb2

GRPC_GENERATED_VERSION = '1.67.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in tra_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FileSyncServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SyncFile = channel.unary_unary(
                '/FileSyncService/SyncFile',
                request_serializer=tra__pb2.FileRequest.SerializeToString,
                response_deserializer=tra__pb2.FileResponse.FromString,
                _registered_method=True)
        self.SyncDirectory = channel.unary_unary(
                '/FileSyncService/SyncDirectory',
                request_serializer=tra__pb2.DirectoryRequest.SerializeToString,
                response_deserializer=tra__pb2.DirectoryResponse.FromString,
                _registered_method=True)
        self.DeleteFile = channel.unary_unary(
                '/FileSyncService/DeleteFile',
                request_serializer=tra__pb2.DeleteRequest.SerializeToString,
                response_deserializer=tra__pb2.DeleteResponse.FromString,
                _registered_method=True)


class FileSyncServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SyncFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SyncDirectory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FileSyncServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SyncFile': grpc.unary_unary_rpc_method_handler(
                    servicer.SyncFile,
                    request_deserializer=tra__pb2.FileRequest.FromString,
                    response_serializer=tra__pb2.FileResponse.SerializeToString,
            ),
            'SyncDirectory': grpc.unary_unary_rpc_method_handler(
                    servicer.SyncDirectory,
                    request_deserializer=tra__pb2.DirectoryRequest.FromString,
                    response_serializer=tra__pb2.DirectoryResponse.SerializeToString,
            ),
            'DeleteFile': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteFile,
                    request_deserializer=tra__pb2.DeleteRequest.FromString,
                    response_serializer=tra__pb2.DeleteResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'FileSyncService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('FileSyncService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FileSyncService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SyncFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/FileSyncService/SyncFile',
            tra__pb2.FileRequest.SerializeToString,
            tra__pb2.FileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SyncDirectory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/FileSyncService/SyncDirectory',
            tra__pb2.DirectoryRequest.SerializeToString,
            tra__pb2.DirectoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/FileSyncService/DeleteFile',
            tra__pb2.DeleteRequest.SerializeToString,
            tra__pb2.DeleteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
